/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesNewRouteImport } from './routes/sites.new'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'

const TunnelsLazyRouteImport = createFileRoute('/tunnels')()
const TimelineLazyRouteImport = createFileRoute('/timeline')()
const SitesLazyRouteImport = createFileRoute('/sites')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const ReportsLazyRouteImport = createFileRoute('/reports')()
const EventsLazyRouteImport = createFileRoute('/events')()
const DevicesLazyRouteImport = createFileRoute('/devices')()
const AlertingLazyRouteImport = createFileRoute('/alerting')()

const TunnelsLazyRoute = TunnelsLazyRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tunnels.lazy').then((d) => d.Route))
const TimelineLazyRoute = TimelineLazyRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/timeline.lazy').then((d) => d.Route))
const SitesLazyRoute = SitesLazyRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sites.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ReportsLazyRoute = ReportsLazyRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reports.lazy').then((d) => d.Route))
const EventsLazyRoute = EventsLazyRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events.lazy').then((d) => d.Route))
const DevicesLazyRoute = DevicesLazyRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices.lazy').then((d) => d.Route))
const AlertingLazyRoute = AlertingLazyRouteImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alerting.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SitesLazyRoute,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => SitesLazyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerting': typeof AlertingLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/events': typeof EventsLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/sites': typeof SitesLazyRouteWithChildren
  '/timeline': typeof TimelineLazyRoute
  '/tunnels': typeof TunnelsLazyRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerting': typeof AlertingLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/events': typeof EventsLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/sites': typeof SitesLazyRouteWithChildren
  '/timeline': typeof TimelineLazyRoute
  '/tunnels': typeof TunnelsLazyRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerting': typeof AlertingLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/events': typeof EventsLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/sites': typeof SitesLazyRouteWithChildren
  '/timeline': typeof TimelineLazyRoute
  '/tunnels': typeof TunnelsLazyRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AlertingLazyRoute: typeof AlertingLazyRoute
  DevicesLazyRoute: typeof DevicesLazyRoute
  EventsLazyRoute: typeof EventsLazyRoute
  ReportsLazyRoute: typeof ReportsLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  SitesLazyRoute: typeof SitesLazyRouteWithChildren
  TimelineLazyRoute: typeof TimelineLazyRoute
  TunnelsLazyRoute: typeof TunnelsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnels': {
      id: '/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof TunnelsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerting': {
      id: '/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AlertingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof SitesLazyRoute
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof SitesLazyRoute
    }
  }
}

interface SitesLazyRouteChildren {
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesNewRoute: typeof SitesNewRoute
}

const SitesLazyRouteChildren: SitesLazyRouteChildren = {
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesNewRoute: SitesNewRoute,
}

const SitesLazyRouteWithChildren = SitesLazyRoute._addFileChildren(
  SitesLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AlertingLazyRoute: AlertingLazyRoute,
  DevicesLazyRoute: DevicesLazyRoute,
  EventsLazyRoute: EventsLazyRoute,
  ReportsLazyRoute: ReportsLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  SitesLazyRoute: SitesLazyRouteWithChildren,
  TimelineLazyRoute: TimelineLazyRoute,
  TunnelsLazyRoute: TunnelsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
