/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunnelsRouteImport } from './routes/tunnels'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AlertingRouteImport } from './routes/alerting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesNewRouteImport } from './routes/sites.new'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'

const TunnelsRoute = TunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertingRoute = AlertingRouteImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SitesRoute,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => SitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/devices': typeof DevicesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/tunnels': typeof TunnelsRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/devices': typeof DevicesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/tunnels': typeof TunnelsRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/devices': typeof DevicesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/tunnels': typeof TunnelsRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/login'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/login'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  id:
    | '__root__'
    | '/'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/login'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertingRoute: typeof AlertingRoute
  DevicesRoute: typeof DevicesRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRouteWithChildren
  TimelineRoute: typeof TimelineRoute
  TunnelsRoute: typeof TunnelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnels': {
      id: '/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof TunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerting': {
      id: '/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AlertingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof SitesRoute
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof SitesRoute
    }
  }
}

interface SitesRouteChildren {
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesNewRoute: typeof SitesNewRoute
}

const SitesRouteChildren: SitesRouteChildren = {
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesNewRoute: SitesNewRoute,
}

const SitesRouteWithChildren = SitesRoute._addFileChildren(SitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertingRoute: AlertingRoute,
  DevicesRoute: DevicesRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRouteWithChildren,
  TimelineRoute: TimelineRoute,
  TunnelsRoute: TunnelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
