/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root.lazy'

const TunnelsLazyRouteImport = createFileRoute('/tunnels')()
const TimelineLazyRouteImport = createFileRoute('/timeline')()
const SitesLazyRouteImport = createFileRoute('/sites')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const ReportsLazyRouteImport = createFileRoute('/reports')()
const LoginLazyRouteImport = createFileRoute('/login')()
const EventsLazyRouteImport = createFileRoute('/events')()
const DevicesLazyRouteImport = createFileRoute('/devices')()
const AlertingLazyRouteImport = createFileRoute('/alerting')()
const IndexLazyRouteImport = createFileRoute('/')()
const SitesNewLazyRouteImport = createFileRoute('/sites/new')()
const SitesSiteIdLazyRouteImport = createFileRoute('/sites/$siteId')()

const TunnelsLazyRoute = TunnelsLazyRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tunnels.lazy').then((d) => d.Route))
const TimelineLazyRoute = TimelineLazyRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/timeline.lazy').then((d) => d.Route))
const SitesLazyRoute = SitesLazyRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sites.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ReportsLazyRoute = ReportsLazyRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reports.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const EventsLazyRoute = EventsLazyRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events.lazy').then((d) => d.Route))
const DevicesLazyRoute = DevicesLazyRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices.lazy').then((d) => d.Route))
const AlertingLazyRoute = AlertingLazyRouteImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/alerting.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const SitesNewLazyRoute = SitesNewLazyRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SitesLazyRoute,
} as any).lazy(() => import('./routes/sites.new.lazy').then((d) => d.Route))
const SitesSiteIdLazyRoute = SitesSiteIdLazyRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => SitesLazyRoute,
} as any).lazy(() => import('./routes/sites.$siteId.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/alerting': typeof AlertingLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/events': typeof EventsLazyRoute
  '/login': typeof LoginLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/sites': typeof SitesLazyRouteWithChildren
  '/timeline': typeof TimelineLazyRoute
  '/tunnels': typeof TunnelsLazyRoute
  '/sites/$siteId': typeof SitesSiteIdLazyRoute
  '/sites/new': typeof SitesNewLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/alerting': typeof AlertingLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/events': typeof EventsLazyRoute
  '/login': typeof LoginLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/sites': typeof SitesLazyRouteWithChildren
  '/timeline': typeof TimelineLazyRoute
  '/tunnels': typeof TunnelsLazyRoute
  '/sites/$siteId': typeof SitesSiteIdLazyRoute
  '/sites/new': typeof SitesNewLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/alerting': typeof AlertingLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/events': typeof EventsLazyRoute
  '/login': typeof LoginLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/sites': typeof SitesLazyRouteWithChildren
  '/timeline': typeof TimelineLazyRoute
  '/tunnels': typeof TunnelsLazyRoute
  '/sites/$siteId': typeof SitesSiteIdLazyRoute
  '/sites/new': typeof SitesNewLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/login'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/login'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  id:
    | '__root__'
    | '/'
    | '/alerting'
    | '/devices'
    | '/events'
    | '/login'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/timeline'
    | '/tunnels'
    | '/sites/$siteId'
    | '/sites/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlertingLazyRoute: typeof AlertingLazyRoute
  DevicesLazyRoute: typeof DevicesLazyRoute
  EventsLazyRoute: typeof EventsLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ReportsLazyRoute: typeof ReportsLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  SitesLazyRoute: typeof SitesLazyRouteWithChildren
  TimelineLazyRoute: typeof TimelineLazyRoute
  TunnelsLazyRoute: typeof TunnelsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnels': {
      id: '/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof TunnelsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerting': {
      id: '/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AlertingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewLazyRouteImport
      parentRoute: typeof SitesLazyRoute
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdLazyRouteImport
      parentRoute: typeof SitesLazyRoute
    }
  }
}

interface SitesLazyRouteChildren {
  SitesSiteIdLazyRoute: typeof SitesSiteIdLazyRoute
  SitesNewLazyRoute: typeof SitesNewLazyRoute
}

const SitesLazyRouteChildren: SitesLazyRouteChildren = {
  SitesSiteIdLazyRoute: SitesSiteIdLazyRoute,
  SitesNewLazyRoute: SitesNewLazyRoute,
}

const SitesLazyRouteWithChildren = SitesLazyRoute._addFileChildren(
  SitesLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlertingLazyRoute: AlertingLazyRoute,
  DevicesLazyRoute: DevicesLazyRoute,
  EventsLazyRoute: EventsLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ReportsLazyRoute: ReportsLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  SitesLazyRoute: SitesLazyRouteWithChildren,
  TimelineLazyRoute: TimelineLazyRoute,
  TunnelsLazyRoute: TunnelsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
